import Head from 'next/head'
import Ball from '@/components/Ball'
import Navbar from '@/components/Navbar'
import dynamic from 'next/dynamic'



export default function Home() {

  const DynamicBall = dynamic(() => import('../components/Ball'), { //per rendering in browser
    ssr: false
  })

  return (
    <div div className='m-0 p-0 box-border overflow-x-hidden'>
      <Head>
        <title>3D Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DynamicBall />
      <Navbar/>
      <h1 className='title font-bold text-white z-10 absolute text-3xl left-[50%] top-[20%] transform translate-x-[-50%] translate-y-[-25%]'>Give it a spin</h1>
      <Ball/>
     
    </div>
  )
}
